API_KEY_ID = 'PKCFAAJF351PZCGEY1BV'
API_SECRET_KEY = '25X4FF041TDjVTnAzCZNIFYOwF0WCRlFKYkQaFdZ'
HEADERS = {
    'APCA-API-KEY-ID': API_KEY_ID,
    'APCA-API-SECRET-KEY': API_SECRET_KEY
}
ALPACA_BASE_URL = 'https://paper-api.alpaca.markets'
DAT_URL = 'https://data.alpaca.markets/v2'
